version: '3'
services:
  ingress:
    image: nginx:1-alpine
    volumes:
      - ./conf/nginx/local-ingress.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app1
      - api1
  app1:
    build: ./client/app1/.
    image: kenfdev/istio-sample:app1-dev
  api1:
    build: ./api/api1/.
    image: kenfdev/istio-sample-api1
    #ports: 
    #  - 8081:8080
    environment:
      SERVER_PORT: 8080
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: my_database
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    #ports:
    #  - 5432:5432
    environment:
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user