version: '3'
services:
  api1:
    build: ./api/api1/.
    image: kenfdev/istio-sample-api1
    ports: 
      - 8081:8080
    environment:
      SERVER_PORT: 8080
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: my_database
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password