apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
data:
  # echo -n rootpassword | base64
  rootpassword: cm9vdHBhc3N3b3Jk
  # echo -n my_user | base64
  user: bXlfdXNlcg==
  # echo -n my_password | base64
  password: bXlfcGFzc3dvcmQ=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  # echo -n my_user | base64
  user: bXlfdXNlcg==
  # echo -n my_password | base64
  password: bXlfcGFzc3dvcmQ=
type: Opaque